<?php

namespace Todo\TodoBundle\Entity;

use Todo\TodoBundle\Entity\Todo;

/**
 * TodoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TodoRepository extends \Doctrine\ORM\EntityRepository
{
    public function deleteTodo($id)
    {
        return $this->createQueryBuilder('t')
                ->delete('TodoBundle:Todo', 't')
                ->andWhere('t.id = :id')
                ->setParameter('id', $id)
                ->getQuery()
                ->execute();
    }

    public function updateTodo($id, array $parameters)
    {
        return $this->createQueryBuilder('t')
                ->update('TodoBundle:Todo', 't')
                ->set('t.todo', ':todo')
                ->set('t.active', ':active')
                ->where('t.id = :id1')
                ->setParameter('todo', $parameters['todo'])
                ->setParameter('active', $parameters['active'])
                ->setParameter('id1', $id)
                ->getQuery()
                ->execute();
    }

}
